name: spc_uq
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8
  - pytorch=2.1.2
  - torchvision=0.16.2
  - torchaudio=2.1.2
  - pytorch-cuda=11.8
  - numpy=1.23
  - scipy=1.9
  - scikit-learn=1.3
  - pandas=2.0
  - matplotlib=3.6
  - seaborn=0.13
  - pillow
  - tqdm
  - requests
  - pyyaml
  - pip
  - pip:
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - google-auth-oauthlib==1.0.0
      - h5py==3.11.0
      - psutil==7.0.0
